/**
 * 시드 데모 후보 mock 분류 + 승인 + 리포트 생성 (OpenAI 불필요)
 * 실행: npm run classify:seed
 */
import { applyClassificationToCandidate } from "../src/lib/candidates/classifyService";
import { updateReviewStatus } from "../src/lib/candidates/reviewService";
import { parseLlmClassifyOutput } from "../src/lib/openai/classifySchema";
import { generateProjectReport } from "../src/lib/report/reportService";
import { landscapeStorage } from "../src/lib/storage/landscapeStorage";
import type { LlmCandidateType } from "../src/types";
import {
  DEMO_CANDIDATES,
  DEMO_COMPANY,
} from "./demo-constants";

const TYPE_BY_COMPANY: Record<string, LlmCandidateType> = {
  "Rival mRNA Corp": "Direct Competitor",
  "Listed Oncology Inc": "Comparable Listed Company",
  "Pending Peer Ltd": "Direct Competitor",
};

const SCORES: Record<LlmCandidateType, number[]> = {
  "Direct Competitor": [85, 80, 70, 60, 50, 55, 45, 65],
  "Indirect Competitor": [65, 60, 55, 50, 40, 45, 35, 55],
  "Comparable Listed Company": [60, 70, 75, 80, 40, 50, 90, 70],
  "Comparable Private Company": [55, 50, 60, 55, 70, 65, 30, 50],
  "Not Relevant": [20, 15, 10, 10, 5, 5, 5, 10],
};

function mockJson(companyName: string, type: LlmCandidateType): string {
  const [
    technologySimilarityScore,
    marketSimilarityScore,
    businessModelSimilarityScore,
    stageSimilarityScore,
    fundingMnaRelevanceScore,
    strategicBuyerInvestorFitScore,
    valuationUsabilityScore,
    geographyRegulatorySimilarityScore,
  ] = SCORES[type];

  return JSON.stringify({
    candidateType: type,
    confidence: 0.75,
    rationale: `Mock classification for ${companyName} (classify:seed).`,
    caveat: "Generated by classify:seed for local testing.",
    technologySimilarityScore,
    marketSimilarityScore,
    businessModelSimilarityScore,
    stageSimilarityScore,
    fundingMnaRelevanceScore,
    strategicBuyerInvestorFitScore,
    valuationUsabilityScore,
    geographyRegulatorySimilarityScore,
  });
}

async function main() {
  const project = (await landscapeStorage.getAll()).find(
    (p) => p.target.companyName === DEMO_COMPANY
  );

  if (!project) {
    console.error(`classify:seed: demo project not found. Run npm run seed first.`);
    process.exit(1);
  }

  const candidates = [...project.candidates];
  let classified = 0;

  for (let i = 0; i < candidates.length; i++) {
    const candidate = candidates[i];
    if (candidate.candidateType !== "Unclassified") continue;

    const type =
      TYPE_BY_COMPANY[candidate.companyName] ?? "Indirect Competitor";
    const classification = parseLlmClassifyOutput(
      mockJson(candidate.companyName, type)
    );
    candidates[i] = applyClassificationToCandidate(
      candidate,
      classification,
      project.target.analysisPurpose
    );
    classified += 1;
    console.log(`  ${candidate.companyName} → ${type}`);
  }

  if (classified === 0) {
    console.log("classify:seed: no Unclassified candidates (already classified).");
  } else {
    await landscapeStorage.update(project.id, { candidates });
    console.log(`Classified ${classified} candidate(s).`);
  }

  const fresh = await landscapeStorage.getById(project.id);
  if (!fresh) throw new Error("project not found");

  for (const item of DEMO_CANDIDATES) {
    if (item.reviewStatus !== "Approved") continue;
    const c = fresh.candidates.find((x) => x.companyName === item.companyName);
    if (c && c.reviewStatus !== "Approved") {
      await updateReviewStatus(project.id, c.id, "Approved");
      console.log(`  Approved: ${item.companyName}`);
    }
  }

  await generateProjectReport(project.id, {
    includePendingInAppendix: true,
    skipImplications: true,
  });

  const loaded = await landscapeStorage.getById(project.id);
  const approved = loaded!.candidates.filter(
    (c) => c.reviewStatus === "Approved"
  ).length;

  console.log("classify:seed: OK");
  console.log(`  Project ID: ${project.id}`);
  console.log(`  Approved:   ${approved} / ${loaded!.candidates.length}`);
  console.log(`  Report:     generated`);
}

main().catch((error) => {
  console.error("classify:seed: FAILED", error);
  process.exit(1);
});
