/**
 * Unclassified 후보 mock 분류 (OpenAI 호출 없음)
 * 실행: npm run mock:classify
 */
import { applyClassificationToCandidate } from "../src/lib/candidates/classifyService";
import { parseLlmClassifyOutput } from "../src/lib/openai/classifySchema";
import { landscapeStorage } from "../src/lib/storage/landscapeStorage";
import type { LlmCandidateType } from "../src/types";

const MOCK_TYPES: LlmCandidateType[] = [
  "Direct Competitor",
  "Indirect Competitor",
  "Comparable Listed Company",
  "Comparable Private Company",
];

function mockJsonForType(type: LlmCandidateType, companyName: string): string {
  const scores: Record<LlmCandidateType, number[]> = {
    "Direct Competitor": [85, 80, 70, 60, 50, 55, 45, 65],
    "Indirect Competitor": [65, 60, 55, 50, 40, 45, 35, 55],
    "Comparable Listed Company": [60, 70, 75, 80, 40, 50, 90, 70],
    "Comparable Private Company": [55, 50, 60, 55, 70, 65, 30, 50],
    "Not Relevant": [20, 15, 10, 10, 5, 5, 5, 10],
  };
  const [
    technologySimilarityScore,
    marketSimilarityScore,
    businessModelSimilarityScore,
    stageSimilarityScore,
    fundingMnaRelevanceScore,
    strategicBuyerInvestorFitScore,
    valuationUsabilityScore,
    geographyRegulatorySimilarityScore,
  ] = scores[type];

  return JSON.stringify({
    candidateType: type,
    confidence: 0.75,
    rationale: `Mock classification for ${companyName} (no OpenAI).`,
    caveat: "Generated by mock:classify script for local testing.",
    technologySimilarityScore,
    marketSimilarityScore,
    businessModelSimilarityScore,
    stageSimilarityScore,
    fundingMnaRelevanceScore,
    strategicBuyerInvestorFitScore,
    valuationUsabilityScore,
    geographyRegulatorySimilarityScore,
  });
}

async function main() {
  const projects = await landscapeStorage.getAll();
  let total = 0;

  for (const project of projects) {
    const unclassified = project.candidates.filter(
      (c) => c.candidateType === "Unclassified"
    );
    if (unclassified.length === 0) continue;

    const candidates = [...project.candidates];
    let changed = false;

    for (let i = 0; i < candidates.length; i++) {
      const candidate = candidates[i];
      if (candidate.candidateType !== "Unclassified") continue;

      const type = MOCK_TYPES[total % MOCK_TYPES.length];
      const classification = parseLlmClassifyOutput(
        mockJsonForType(type, candidate.companyName)
      );
      candidates[i] = applyClassificationToCandidate(
        candidate,
        classification,
        project.target.analysisPurpose
      );
      total += 1;
      changed = true;
      console.log(`  ${candidate.companyName} → ${type}`);
    }

    if (changed) {
      await landscapeStorage.update(project.id, { candidates });
      console.log(`Project: ${project.target.companyName}`);
    }
  }

  if (total === 0) {
    console.log("Mock classify: no Unclassified candidates found.");
  } else {
    console.log(`Mock classify: OK (${total} candidate(s))`);
  }
}

main().catch((error) => {
  console.error("Mock classify: FAILED", error);
  process.exit(1);
});
